"""Topic quiz metadata and question banks.

Each bank has more than 10 unique items so every attempt can sample a
different mix. Questions are (prompt, options, correct_index, explanation).
"""

QUIZZES = {
    "variables": ("Variables Quiz", "Variables"),
    "data-types": ("Data Types Quiz", "Data Types"),
    "operators": ("Operators Quiz", "Operators"),
    "conditions": ("Conditions Quiz", "Conditions"),
    "loops": ("Loops Quiz", "Loops"),
    "strings": ("Strings Quiz", "Strings"),
    "lists": ("Lists Quiz", "Lists"),
    "dictionaries": ("Dictionaries Quiz", "Dictionaries"),
    "functions": ("Functions Quiz", "Functions"),
    "oop": ("OOP Quiz", "Object-Oriented Programming"),
    "advanced": ("Advanced Python Quiz", "Advanced Python"),
}

QUESTIONS_PER_QUIZ = 10

QUESTION_BANKS = {
    "variables": [
        ("What is a variable?", ["A labeled place to store a value", "A Python error", "A web browser", "A loop"], 0, "A variable gives a value a useful name."),
        ("Which is a clear variable name?", ["2name", "student_name", "student name", "print"], 1, "Use letters, numbers, and underscores; start with a letter."),
        ("What does name = 'Ada' do?", ["Prints Ada", "Stores Ada in name", "Deletes name", "Creates a loop"], 1, "The equals sign assigns a value to a variable."),
        ("Which function shows a value on the screen?", ["show()", "print()", "output()", "write()"], 1, "print() displays a value in the output."),
        ("Can you change the value stored in a variable later?", ["Yes, by assigning a new value", "No, never", "Only if it is a number", "Only once"], 0, "Assignment updates the name to point at a new value."),
        ("Which assignment is valid Python?", ["x == 5", "x = 5", "5 = x", "let x = 5"], 1, "A single equals sign assigns a value."),
        ("What happens if you print a name that was never created?", ["Python invents a value", "You get a NameError", "The program prints None", "Python creates an empty string"], 1, "Using a name before it exists raises NameError."),
        ("Why use meaningful variable names?", ["They make code easier to read", "Python runs faster", "They replace comments always", "They hide errors"], 0, "Clear names explain what the value represents."),
        ("What does score += 1 do if score is 4?", ["Sets score to 1", "Sets score to 5", "Deletes score", "Prints 4"], 1, "+= adds to the current value, so 4 becomes 5."),
        ("Which name is not allowed?", ["total_cost", "class", "item2", "_hidden"], 1, "class is a reserved keyword."),
        ("What is stored in x after x = 10 then x = 20?", ["10", "20", "Both 10 and 20", "Nothing"], 1, "A name holds the most recent assigned value."),
        ("How do you copy a value from one variable to another?", ["b = a", "copy a b", "a == b", "swap a, b always"], 0, "Assignment copies the value on the right into the name on the left."),
        ("What is a good first step before using a variable?", ["Give it a value with =", "Delete it", "Print random text", "Import it from a loop"], 0, "Create and assign the name before you use it."),
        ("Which statement creates a variable called city?", ["city == 'Paris'", "city = 'Paris'", "'Paris' = city", "var city Paris"], 1, "name = value creates and fills the variable."),
        ("What does del count do?", ["Prints count", "Removes the name count", "Sets count to 0", "Creates count"], 1, "del removes that name from the current scope."),
        ("Can two variables hold the same value?", ["Yes", "No", "Only strings", "Only once per program"], 0, "Many names can store the same kind of value."),
        ("What is snake_case used for in Python?", ["Variable and function names", "Class names only", "File types", "Error messages"], 0, "Python style uses lowercase_with_underscores for most names."),
        ("After a = 3 and b = a, if a = 7, what is b?", ["7", "3", "10", "None"], 1, "b received the earlier integer 3; later changes to a do not update b."),
    ],
    "data-types": [
        ("Which value is an integer?", ["'7'", "7", "7.0", "True"], 1, "Integers are whole numbers without a decimal point."),
        ("Which type stores text?", ["int", "str", "float", "bool"], 1, "str is the Python name for text strings."),
        ("What type is True?", ["str", "int", "bool", "None"], 2, "True and False are Boolean values."),
        ("What does type() help you discover?", ["A value's data type", "A file name", "A loop", "A comment"], 0, "type() reports the kind of value."),
        ("Which value is a float?", ["3", "'3.0'", "3.0", "False"], 2, "Floats have a decimal point."),
        ("What type is None?", ["int", "NoneType", "str", "bool"], 1, "None is a special empty value of type NoneType."),
        ("Which conversion turns '12' into an integer?", ["int('12')", "str(12)", "float only", "bool('12')"], 0, "int() parses a whole-number string."),
        ("What is the type of 2 + 3.0?", ["int", "float", "str", "bool"], 1, "Mixing int and float produces a float."),
        ("Which is a Boolean?", ["'False'", "False", "0.0 as text", "none"], 1, "False without quotes is the Boolean value."),
        ("What does bool(0) return?", ["True", "False", "0", "None"], 1, "Zero is treated as false."),
        ("What does bool('hello') return?", ["False", "True", "Error", "None"], 1, "Non-empty strings are true."),
        ("Which call turns 9 into text?", ["str(9)", "int(9)", "float(9)", "bool(9)"], 0, "str() makes a string."),
        ("What type is [1, 2, 3]?", ["tuple", "list", "dict", "set"], 1, "Square brackets create a list."),
        ("What type is (1, 2)?", ["list", "tuple", "dict", "str"], 1, "Parentheses with commas create a tuple."),
        ("Which value cannot be changed after creation?", ["list", "dict", "tuple", "set"], 2, "Tuples are immutable."),
        ("What does float('3.5') produce?", ["3", "3.5", "'3.5'", "True"], 1, "float() converts a decimal string to a number."),
        ("Which is not a built-in data type?", ["int", "loop", "str", "list"], 1, "loop is a concept, not a type."),
        ("What type is {'a': 1}?", ["list", "tuple", "dict", "str"], 2, "Curly braces with keys create a dictionary."),
    ],
    "operators": [
        ("What does + do with numbers?", ["Adds", "Multiplies", "Compares", "Comments"], 0, "+ adds numeric values."),
        ("Which operator checks equality?", ["=", "==", "+=", "!="], 1, "== compares two values."),
        ("What is 10 % 3?", ["3", "1", "0", "10"], 1, "% gives the remainder after division."),
        ("What runs first in 2 + 3 * 4?", ["Addition", "Multiplication", "Nothing", "Comparison"], 1, "Multiplication has higher precedence."),
        ("What does != mean?", ["Assign", "Not equal", "Less than", "Floor divide"], 1, "!= is true when values differ."),
        ("What is 2 ** 3?", ["6", "8", "9", "5"], 1, "** is exponentiation: 2 to the power 3 is 8."),
        ("What is 7 // 2?", ["3.5", "3", "4", "1"], 1, "// is floor division and drops the fraction."),
        ("Which operator means 'and both must be true'?", ["or", "and", "not", "=="], 1, "and requires both sides to be true."),
        ("What does not True produce?", ["True", "False", "None", "0"], 1, "not flips a Boolean."),
        ("What is 5 > 3?", ["False", "True", "5", "3"], 1, "5 is greater than 3."),
        ("Which operator assigns a value?", ["==", "=", "!=", "<="], 1, "A single = assigns."),
        ("What is 8 / 2?", ["4", "4.0", "0", "16"], 1, "Regular / always produces a float in Python 3."),
        ("What does or do?", ["True if at least one side is true", "True only if both are true", "Flips a value", "Multiplies"], 0, "or succeeds if any operand is true."),
        ("What is 15 % 5?", ["3", "0", "5", "1"], 1, "15 divides evenly by 5, so the remainder is 0."),
        ("Which comparison means 'less than or equal'?", ["<", "<=", ">=", "<>"], 1, "<= covers less than and equal."),
        ("What does += combine?", ["Addition and assignment", "Only comparison", "Only multiplication", "String slicing"], 0, "x += 1 is the same idea as x = x + 1."),
        ("What is True and False?", ["True", "False", "None", "Error"], 1, "and is true only when both sides are true."),
        ("Parentheses in  (2 + 3) * 4 change what?", ["Which operation happens first", "The variable type", "The file name", "The comment style"], 0, "Parentheses override default precedence."),
    ],
    "conditions": [
        ("Which keyword starts a condition?", ["when", "if", "check", "then"], 1, "if begins a conditional statement."),
        ("What is else used for?", ["Repeat code", "Run when if is false", "Create a list", "Import code"], 1, "else handles the other case."),
        ("What does == mean?", ["Assign", "Compare equality", "Add", "Not equal"], 1, "== asks whether values are equal."),
        ("Why use indentation after if?", ["It marks the block of code", "It is decoration", "It imports Python", "It ends a loop"], 0, "Indented lines belong to the condition."),
        ("Which keyword tests another condition after if?", ["elif", "elseif", "else if only", "when"], 0, "elif means else if."),
        ("What runs if the if test is False and there is no else?", ["The if block", "Nothing in that if/else", "Python crashes", "The next elif always"], 1, "A false test skips the indented block."),
        ("Which test checks whether x is greater than 10?", ["x = 10", "x > 10", "x + 10", "x == '10' always"], 1, "> compares numbers."),
        ("Can you nest if inside another if?", ["Yes", "No", "Only in functions", "Only with lists"], 0, "Inner conditions are allowed."),
        ("What should follow if age >= 18: ?", ["An indented block", "A closing bracket", "A semicolon", "The word then"], 0, "The colon starts an indented suite."),
        ("What is a truthy value?", ["A value treated as True in a condition", "Always the number 1", "Only True itself", "An error"], 0, "Non-empty strings and non-zero numbers are truthy."),
        ("What is a falsy value?", ["0, empty string, None, False", "Any string", "Any list", "The number 1"], 0, "These values fail an if test."),
        ("How many else blocks can one if have?", ["Unlimited", "One", "Two", "None ever"], 1, "An if can have at most one else."),
        ("What does pass do in an if block?", ["Does nothing on purpose", "Stops Python", "Prints True", "Repeats the test"], 0, "pass is a placeholder statement."),
        ("Which is a valid condition?", ["if x > 0:", "if x > 0", "if (x > 0)", "if x > 0 then:"], 0, "Python needs a colon after the test."),
        ("What happens with if / elif / else?", ["Python runs the first matching branch", "All branches run", "Only else runs", "None run"], 0, "The first true test wins; the rest are skipped."),
        ("How do you combine two tests that both must pass?", ["if a and b:", "if a or b:", "if not a:", "if a = b:"], 0, "and requires both conditions."),
        ("What does if not ready: mean?", ["Run when ready is false", "Run when ready is true", "Always run", "Create ready"], 0, "not inverts the test."),
        ("Why compare with == instead of = inside if?", ["= assigns; == compares", "They are identical", "== assigns", "= only prints"], 0, "Using = in a condition is a syntax error in Python."),
    ],
    "loops": [
        ("What is a loop for?", ["Repeating work", "Making comments", "Naming a variable", "Closing Python"], 0, "Loops repeat a block of instructions."),
        ("Which loop works through a list?", ["for", "if", "try", "def"], 0, "for visits each item."),
        ("What does break do?", ["Stops the loop", "Restarts Python", "Prints text", "Adds an item"], 0, "break exits the nearest loop."),
        ("What does range(3) produce?", ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3"], 0, "range starts at zero and stops before 3."),
        ("What does continue do?", ["Skips the rest of this iteration", "Ends the program", "Creates a list", "Defines a function"], 0, "continue jumps to the next cycle."),
        ("When does a while loop keep running?", ["While its condition is true", "Exactly three times", "Until Python closes", "Only once"], 0, "while repeats as long as the test stays true."),
        ("What is an infinite loop?", ["A loop that never stops on its own", "A loop that runs twice", "A sorted list", "A comment"], 0, "The condition never becomes false."),
        ("What does range(1, 5) produce?", ["1, 2, 3, 4", "1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "5"], 0, "The stop value is excluded."),
        ("Which loop is better when you know the collection?", ["for", "while only", "if", "class"], 0, "for is natural for items in a sequence."),
        ("What does enumerate() add?", ["An index together with each item", "A random number", "A file", "A class"], 0, "enumerate pairs a count with each value."),
        ("Can you put a loop inside another loop?", ["Yes, that is a nested loop", "No", "Only while inside for", "Only in files"], 0, "Nested loops are allowed."),
        ("What does range(0, 10, 2) count by?", ["2", "10", "0", "1"], 0, "The third argument is the step."),
        ("How do you loop 5 times with for?", ["for i in range(5):", "for i in 5:", "for 5 times:", "loop 5:"], 0, "range(5) yields five numbers."),
        ("What should a while loop usually do inside the body?", ["Update something so the condition can become false", "Print only once", "Delete Python", "Define a class"], 0, "Otherwise it may never end."),
        ("What does else after a for loop mean?", ["Run if the loop did not hit break", "Always skip the loop", "Restart the loop", "Catch errors"], 0, "for/else runs the else when the loop finishes normally."),
        ("Which keyword skips one round but keeps looping?", ["continue", "break", "pass", "return"], 0, "continue does not exit the whole loop."),
        ("What does for letter in 'hi': visit?", ["h then i", "hi as one item only", "2 then 1", "Nothing"], 0, "A string is a sequence of characters."),
        ("Why use zip() in a loop?", ["Walk two lists together", "Compress files only", "Stop a loop", "Create a class"], 0, "zip pairs items from each iterable."),
    ],
    "strings": [
        ("What is a string?", ["Text data", "A number", "A loop", "A file"], 0, "Strings hold text."),
        ("How do you write text in Python?", ["With quotes", "With brackets only", "With a colon", "With a hash"], 0, "Quotes create a string."),
        ("Which joins two strings?", ["+", "/", "%", "=="], 0, "+ concatenates strings."),
        ("What does len('cat') return?", ["2", "3", "4", "cat"], 1, "cat has three characters."),
        ("What is 'Python'[0]?", ["P", "y", "n", "Python"], 0, "Index 0 is the first character."),
        ("What does 'Hello'.upper() return?", ["hello", "HELLO", "Hello", "hELLO"], 1, "upper() makes every letter uppercase."),
        ("What does 'HELLO'.lower() return?", ["HELLO", "hello", "Hello", "h"], 1, "lower() makes letters lowercase."),
        ("Which method removes extra spaces on both ends?", ["strip()", "split()", "replace()", "find()"], 0, "strip() trims edges."),
        ("What does 'a,b'.split(',') produce?", ["['a', 'b']", "'a b'", "['a,b']", "a+b"], 0, "split cuts the string on the separator."),
        ("Are strings mutable in Python?", ["No, you create a new string instead", "Yes, you change letters in place", "Only empty ones", "Only numbers inside them"], 0, "String methods return new strings."),
        ("What does 'hi' * 3 produce?", ["hihihi", "hi3", "3hi", "error"], 0, "Multiplying repeats the text."),
        ("How do you put a quote inside a string?", ["Use the other quote style or an escape", "You cannot", "Use a list", "Use a colon"], 0, "\"He said 'hi'\" or escape with backslash."),
        ("What does 'abc'.replace('b', 'z') return?", ["azc", "abc", "zbz", "z"], 0, "replace swaps matching pieces."),
        ("What does f'Hi {name}' need?", ["A name variable to insert", "A loop", "A file", "A class"], 0, "f-strings fill braces with values."),
        ("What is 'Python'[-1]?", ["n", "P", "y", "o"], 0, "Negative indices count from the end."),
        ("What does 'py' in 'python' check?", ["Whether py appears in python", "Whether they are equal", "The length", "The type"], 0, "in tests for a substring."),
        ("Which is a valid empty string?", ["''", "[]", "{}", "None"], 0, "Two quotes with nothing between them."),
        ("What does 'one two'.title() do?", ["One Two", "ONE TWO", "one two", "One two"], 0, "title() capitalizes each word."),
    ],
    "lists": [
        ("What brackets create a list?", ["[]", "{}", "()", "<>"], 0, "Square brackets create lists."),
        ("List positions start at?", ["0", "1", "-1", "Any number"], 0, "The first index is zero."),
        ("Which adds an item to the end?", ["append()", "print()", "type()", "range()"], 0, "append() adds to the end."),
        ("Can a list change after creation?", ["Yes", "No", "Only text lists", "Only empty lists"], 0, "Lists are mutable."),
        ("What is nums[1] in [10, 20, 30]?", ["10", "20", "30", "1"], 1, "Index 1 is the second item."),
        ("Which method removes and returns the last item?", ["pop()", "append()", "sort()", "len()"], 0, "pop() takes from the end by default."),
        ("What does len([1, 2, 3]) return?", ["2", "3", "4", "1"], 1, "len counts items."),
        ("How do you join two lists?", ["list1 + list2", "list1 * list2", "list1 / list2", "list1 and list2"], 0, "+ concatenates lists."),
        ("What does insert(0, x) do?", ["Puts x at the start", "Deletes x", "Sorts the list", "Prints x"], 0, "insert places an item at an index."),
        ("What does remove(value) do?", ["Deletes the first matching value", "Deletes every copy always", "Sorts values", "Adds value"], 0, "remove searches by value, not index."),
        ("What is slicing nums[1:3] on [a, b, c, d]?", ["[b, c]", "[a, b, c]", "[c, d]", "[b, c, d]"], 0, "The end index is excluded."),
        ("Which method sorts a list in place?", ["sort()", "sorted only as a name", "append()", "split()"], 0, "sort() changes the same list."),
        ("What does sorted(nums) return?", ["A new sorted list", "None always", "A string", "The same list object always"], 0, "sorted() does not change the original."),
        ("How do you loop through items?", ["for item in my_list:", "loop my_list:", "each my_list", "while list:"], 0, "for walks each element."),
        ("What is an empty list?", ["[]", "{}", "()", "''"], 0, "[] has length 0."),
        ("What does 'x' in ['x', 'y'] return?", ["True", "False", "0", "'x'"], 0, "in checks membership."),
        ("What does extend([4, 5]) add?", ["Each item 4 and 5", "One nested list only", "Nothing", "A string"], 0, "extend adds items one by one."),
        ("What is fruits[-1] in ['a', 'b', 'c']?", ["c", "a", "b", "error"], 0, "Negative one is the last item."),
    ],
    "dictionaries": [
        ("A dictionary stores?", ["Key-value pairs", "Only numbers", "Only text", "Loops"], 0, "Each key points to a value."),
        ("Which brackets create a dictionary?", ["{}", "[]", "()", "<>"], 0, "Curly braces create dictionaries."),
        ("What should keys usually be?", ["Unique", "Repeated", "Always lists", "Always numbers"], 0, "Each key identifies one value."),
        ("How do you access a value?", ["With its key", "With a loop only", "With print only", "You cannot"], 0, "Use dictionary[key]."),
        ("What does person['name'] read?", ["The value stored under name", "The length", "All keys", "A list"], 0, "The key is the lookup."),
        ("Which method lists keys?", ["keys()", "append()", "split()", "range()"], 0, "keys() views the keys."),
        ("What happens if you use a missing key with []?", ["KeyError", "None silently always", "False", "0"], 0, "Direct lookup raises KeyError."),
        ("Which lookup avoids KeyError?", ["get()", "append()", "popitem only", "sort()"], 0, "get() returns None or a default."),
        ("Can a list be a dictionary key?", ["No, keys must be immutable", "Yes always", "Only empty lists", "Only of numbers"], 0, "Lists cannot be keys because they can change."),
        ("What does values() give you?", ["The stored values", "Only keys", "A string", "A file"], 0, "values() views the values."),
        ("How do you add a new pair?", ["d['new'] = value", "d.append(value)", "d + value", "d.add only"], 0, "Assignment with a new key inserts it."),
        ("What does del d['x'] do?", ["Removes key x", "Prints x", "Creates x", "Sorts d"], 0, "del deletes that pair."),
        ("What does items() provide?", ["Key-value pairs for looping", "Only numbers", "A class", "A tuple of lists always"], 0, "for k, v in d.items() is common."),
        ("Are dictionaries ordered in modern Python?", ["Yes, they remember insertion order", "No, never", "Only if sorted", "Only with numbers"], 0, "Since Python 3.7, order is preserved."),
        ("What is {} ?", ["An empty dict", "An empty set in this writing", "A list", "A tuple"], 0, "Empty curly braces make a dict."),
        ("What does update() do?", ["Merges another mapping in", "Deletes all keys", "Sorts values", "Converts to a list"], 0, "update copies pairs from another dict."),
        ("Which is a valid key?", ["'city'", "['city']", "{'city'}", "{1, 2}"], 0, "Strings are immutable and work as keys."),
        ("What does pop('age') return?", ["The value for age, then removes it", "All keys", "True", "The dict itself"], 0, "pop removes and returns that value."),
    ],
    "functions": [
        ("What keyword creates a function?", ["def", "func", "make", "return"], 0, "def defines a function."),
        ("Why use functions?", ["Reuse a named task", "Avoid Python", "Only print text", "Create comments"], 0, "Functions organize and reuse code."),
        ("What can return do?", ["Send a value back", "Delete a function", "Start a loop", "Add a comment"], 0, "return gives a result to the caller."),
        ("A parameter is?", ["Input named in a function definition", "Always an error", "A loop", "A file"], 0, "Parameters receive values."),
        ("What is an argument?", ["The value you pass when calling", "The function name only", "A comment", "A module"], 0, "Arguments fill parameters."),
        ("What happens if a function has no return?", ["It returns None", "It returns 0", "It crashes", "It returns the name"], 0, "The default result is None."),
        ("How do you call greet?", ["greet()", "call greet", "def greet", "return greet"], 0, "Parentheses run the function."),
        ("What is a default parameter?", ["A fallback if no argument is given", "A required list", "An error", "A loop"], 0, "def f(x=1) uses 1 when x is omitted."),
        ("What does *args collect?", ["Extra positional arguments", "Only keyword names", "Files", "Classes"], 0, "*args is a tuple of extras."),
        ("What does **kwargs collect?", ["Extra keyword arguments", "Only numbers", "A list of strings always", "Return values"], 0, "**kwargs is a dictionary."),
        ("Why write a docstring?", ["To explain what the function does", "To run the function faster", "To hide errors", "To import Python"], 0, "Docstrings document the function."),
        ("Can a function call another function?", ["Yes", "No", "Only print", "Only once"], 0, "Functions can use other functions."),
        ("What is scope?", ["Where a name is visible", "The file size", "A data type", "A loop counter only"], 0, "Local names live inside the function."),
        ("What does pass do in a function body?", ["Placeholder that does nothing", "Returns True", "Prints pass", "Ends Python"], 0, "Useful while you design the function."),
        ("Which line starts a function named add?", ["def add(a, b):", "function add(a, b)", "add = function", "define add"], 0, "def name(parameters): is the syntax."),
        ("What is a return value used for?", ["So the caller can use the result", "To name a file", "To create a list always", "To stop all loops in the program"], 0, "You can store or print what was returned."),
        ("Can functions have multiple return statements?", ["Yes, but one of them runs", "No", "Only two", "Only in classes"], 0, "The first executed return exits."),
        ("What is a lambda?", ["A small anonymous function", "A loop", "A dictionary", "A module"], 0, "lambda writes a tiny function in one expression."),
    ],
    "oop": [
        ("A class is like?", ["A blueprint", "A printed result", "A loop", "An error"], 0, "A class describes how objects are made."),
        ("An object is?", ["An instance of a class", "Only a variable", "A comment", "A module"], 0, "Objects are created from classes."),
        ("What is self?", ["The current object", "A Python error", "A list", "A keyword for loops"], 0, "self lets methods use the current object's data."),
        ("A method is?", ["A function inside a class", "A text string", "A database", "A comment"], 0, "Methods describe object behavior."),
        ("Which method initializes a new object?", ["__init__", "__str__", "print", "def"], 0, "__init__ runs when you create an instance."),
        ("How do you create an object from Dog?", ["Dog()", "new Dog", "class Dog", "Dog.create always"], 0, "Calling the class builds an instance."),
        ("What is inheritance?", ["A class using another class as a base", "Copying files", "A loop trick", "Deleting a class"], 0, "The child reuses and extends the parent."),
        ("What does super() help with?", ["Calling the parent class", "Sorting lists", "Opening files", "Printing errors"], 0, "super() reaches the base class."),
        ("What is encapsulation?", ["Keeping data with the methods that use it", "Making loops faster", "Hiding Python", "A string method"], 0, "Objects bundle state and behavior."),
        ("What does __str__ control?", ["The readable text for print(object)", "Object deletion", "Math speed", "Import paths"], 0, "__str__ returns a user-friendly string."),
        ("Can a class have many objects?", ["Yes", "No, only one", "Only two", "Only if they are strings"], 0, "Each instance is separate."),
        ("What is an attribute?", ["Data stored on an object", "A for loop", "A module search path", "A comment"], 0, "self.name is an attribute."),
        ("What is polymorphism?", ["Same method name, different class behavior", "One variable type only", "Faster loops", "Hiding files"], 0, "Different objects can share a method name."),
        ("Why use classes?", ["To model real things with data and actions", "To replace all functions", "To avoid names", "To print only"], 0, "Classes structure larger programs."),
        ("What is a class variable?", ["Data shared by all instances", "Data unique to one object always", "A loop counter", "A hidden file"], 0, "Defined on the class, not in __init__ as self."),
        ("What does isinstance(obj, Dog) check?", ["Whether obj is a Dog (or subclass)", "Whether Dog exists as a file", "The length", "The module name"], 0, "isinstance tests types."),
        ("What is composition?", ["Building an object from other objects", "Deleting methods", "A string join", "A tuple index"], 0, "Has-a relationships use other objects as parts."),
        ("Must every method take self?", ["Instance methods do", "No methods ever do", "Only __init__", "Only static ones"], 0, "Ordinary methods receive the instance as self."),
    ],
    "advanced": [
        ("A generator produces values?", ["One at a time", "Only as lists", "Never", "Only text"], 0, "Generators yield values as needed."),
        ("A decorator?", ["Adds behavior to a function", "Deletes a class", "Creates a list", "Prints only"], 0, "Decorators wrap functions."),
        ("Type hints help with?", ["Code clarity and tools", "Running loops faster always", "Deleting bugs automatically", "Installing Python"], 0, "Hints communicate expected types."),
        ("A context manager helps?", ["Manage setup and cleanup", "Create a class only", "Use a for loop", "Name a string"], 0, "with handles resources safely."),
        ("Which keyword produces generator values?", ["yield", "return only", "pass", "async always"], 0, "yield pauses and sends a value."),
        ("What does with open(path) as f: do?", ["Opens then closes the file for you", "Deletes the file", "Creates a class", "Starts a thread"], 0, "The with block closes the file afterward."),
        ("What is a list comprehension?", ["A compact way to build a list", "A type of class", "A decorator", "A file mode"], 0, "[x*2 for x in nums] builds a list."),
        ("What does * in def f(*args) mean?", ["Accept extra positional arguments", "Multiply always", "Require a list", "Start a generator"], 0, "It packs leftover positional args."),
        ("What is an iterator?", ["An object you can walk with next()", "A dictionary key", "A comment", "A module searcher"], 0, "Iterators implement __next__."),
        ("What does @staticmethod mean?", ["A method that does not use self", "A faster loop", "A private file", "A decorator that prints"], 0, "It belongs to the class but needs no instance."),
        ("What is *args vs **kwargs?", ["Tuple of extras vs dict of extras", "Two names for lists", "File flags", "Loop styles"], 0, "One is positional packing, one is keyword packing."),
        ("What does try / except catch?", ["Exceptions so the program can recover", "Only spelling mistakes in comments", "Faster math", "Import order"], 0, "except handles errors you expect."),
        ("What is a lambda used for?", ["A short inline function", "Opening files", "Creating modules", "Sorting disks"], 0, "Useful for simple callbacks."),
        ("What does map() do?", ["Applies a function to each item", "Draws a picture", "Creates a class map", "Opens GPS"], 0, "It transforms an iterable."),
        ("What is a set good for?", ["Unique items and fast membership", "Ordered key-value pairs", "Indexed letters only", "Infinite loops"], 0, "Sets drop duplicates."),
        ("What does async def start?", ["A coroutine you can await", "A normal loop", "A class", "A decorator always"], 0, "Async functions pause while waiting."),
        ("What is __name__ == '__main__' for?", ["Run code only when the file is executed directly", "Import every module", "Hide errors", "Name a class"], 0, "It keeps import-safe scripts."),
        ("What does zip() return?", ["Pairs from each iterable", "A compressed file always", "A sorted list", "A dictionary only"], 0, "zip walks collections in parallel."),
    ],
}
